---
driver:
  name: vagrant
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-11.04
    driver_config:
      box: talifun-ubuntu-11.04
      box_url: http://dl.dropbox.com/u/7490647/talifun-ubuntu-11.04-server-amd64.box
  - name: debian-6.0.8

suites:
  - name: default
    run_list: network_interfaces::default
